-- Verbs table - stores the base verb information
CREATE TABLE public."Verbs" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "Greek" VARCHAR NOT NULL,           -- Greek writing of the verb
  "Russian" VARCHAR NOT NULL,         -- Russian translation of the verb
  "LastCorrect" DATE NULL,            -- Last time answered correctly
  "LastWrong" DATE NULL,              -- Last time answered incorrectly
  "TimesShown" BIGINT DEFAULT 0,      -- Total times shown to user
  "NumberOfCorrect" BIGINT DEFAULT 0, -- Total correct answers
  "NumberOfWrong" BIGINT DEFAULT 0,   -- Total incorrect answers
  "IsVisible" BOOLEAN DEFAULT TRUE,   -- Should it be shown to user or not
  "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- VerbPhrases table - stores phrases/conjugations for each verb
CREATE TABLE public."VerbPhrases" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "VerbId" BIGINT NOT NULL REFERENCES public."Verbs"(id) ON DELETE CASCADE,
  "Greek" VARCHAR NOT NULL,           -- Greek phrase (e.g., "πηγαίνω", "πήγε", "πήγαν;")
  "Russian" VARCHAR NOT NULL,         -- Russian translation (e.g., "я иду", "она ушла", "они ушли?")
  "LastShown" DATE NULL,              -- Last time this phrase was shown
  "LastCorrect" DATE NULL,            -- Last time answered correctly
  "LastWrong" DATE NULL,              -- Last time answered incorrectly
  "TimesShown" BIGINT DEFAULT 0,      -- Total times shown to user
  "NumberOfCorrect" BIGINT DEFAULT 0, -- Total correct answers
  "NumberOfWrong" BIGINT DEFAULT 0,   -- Total incorrect answers
  "Remembered" BOOLEAN NULL,          -- Last answer: true=remembered, false=didn't remember, null=never shown
  "CreatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Index for faster queries on VerbPhrases by VerbId
CREATE INDEX idx_verbphrases_verbid ON public."VerbPhrases"("VerbId");

-- Index for faster queries on visible verbs
CREATE INDEX idx_verbs_isvisible ON public."Verbs"("IsVisible");
